apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-configmap
  namespace: wordpress
data:
  WORDPRESS_DB_HOST: db-service:3306
  WORDPRESS_DB_USER: wpuser
  WORDPRESS_DB_PASSWORD: wppassword
  WORDPRESS_DB_NAME: wpdb
