apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 36000
  type: NodePort
  selector:
    app: wordpress-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
