apiVersion: v1
kind: PersistentVolume
metadata:
  name: db
  namespace: wordpress
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/mysql
