
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: wordpress
spec:
  type: ClusterIP
  selector:
    app: db-server
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
