kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: site
  name: site-role
rules:
- apiGroups: [""]
  resources: ["pv", "pvc", "svc", "deploy", "sts" , "hpa", "pods" , "ing"]
  verbs: ["create", "get", "list", "update", "patch", "delete"]
