apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wp-rolebinding
  namespace: wordpress
subjects:
- kind: ServiceAccount
  name: wp-admin
  apiGroup: ""
roleRef:
  kind: Role
  name: wp-role
  apiGroup: rbac.authorization.k8s.io
